


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Student
 */
public class beers extends javax.swing.JFrame {

    /**
     * Creates new form beers
     */
    public beers() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        j3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        c1 = new javax.swing.JCheckBox();
        c2 = new javax.swing.JCheckBox();
        j1 = new javax.swing.JTextField();
        j2 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        JPanel panel = new JPanel();
        panel.setLayout(null);
        setSize(1500,1000);

        jButton1.setBackground(new java.awt.Color(188, 76, 5));
        jButton1.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        jButton1.setText("Add To Cart");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.setBounds(180, 180, -1, -1);
        panel.add(jButton1);

        jLabel3.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        jLabel3.setText("Total amount");
        jLabel3.setBounds(30, 240, 150, 30);
        panel.add(jLabel3);

        j3.setEditable(false);
        j3.setBounds(370, 230, 90, 40);
        panel.add(j3);

        jLabel1.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(239, 239, 239));
        jLabel1.setText("QTY");
        jLabel1.setBounds(380, 30, -1, -1);
        panel.add(jLabel1);

        jButton2.setBackground(new java.awt.Color(14, 49, 109));
        jButton2.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jButton2.setText("soft drinks");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.setBounds(0, 300, 170, -1);
        panel.add(jButton2);

        jButton3.setBackground(new java.awt.Color(14, 49, 109));
        jButton3.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jButton3.setText("hot beverages");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jButton3.setBounds(0, 340, -1, -1);
        panel.add(jButton3);

        jButton4.setBackground(new java.awt.Color(14, 49, 109));
        jButton4.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jButton4.setText("Generate Bill");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jButton4.setBounds(340, 310, 170, 60);
        panel.add(jButton4);

        c1.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        c1.setForeground(new java.awt.Color(212, 212, 212));
        c1.setText("Phoenix");
        c1.setOpaque(false);
        c1.setBounds(50, 60, 160, -1);
        panel.add(c1);

        c2.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        c2.setForeground(new java.awt.Color(211, 211, 211));
        c2.setText("Guinness");
        c2.setOpaque(false);
        c2.setBounds(50, 100, -1, -1);
        panel.add(c2);

        j1.setText("0");
        j1.setBounds(380, 60, 30, 30);
        panel.add(j1);

        j2.setText("0");
        j2.setBounds(380, 100, 30, 30);
        panel.add(j2);

        jButton6.setBackground(new java.awt.Color(14, 49, 109));
        jButton6.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jButton6.setText("menu");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jButton6.setBounds(340, 380, 170, -1);
        panel.add(jButton6);

        jButton7.setBackground(new java.awt.Color(14, 49, 109));
        jButton7.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jButton7.setText("hookah");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jButton7.setBounds(0, 380, 170, -1);
        panel.add(jButton7);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Student\\Desktop\\New folder (2)\\bhau beer bottle.jpg")); // NOI18N
        jLabel4.setOpaque(true);
        jLabel4.setBounds(0, -10, 510, 430);
        panel.add(jLabel4);
        pack();
        getContentPane().add(panel);
        setVisible(true);
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {

        String item="0";
        String cat="beer";
        int q=0,qq=0,amt1=0,amt2=0;
        double total=0.0;
        q=Integer.parseInt(j1.getText());
        qq=Integer.parseInt(j2.getText());
        if(c2.isSelected())
            amt2=qq*160;
        if(c1.isSelected())
        {amt1=q*155;}

        total=amt1+amt2;
        j3.setText(" "+total);
        if(c1.isSelected())
        {
            try
            {Class.forName("java.sql.DriverManager");
                Connection con=DriverManager.getConnection("jdbc:MySQL://localhost:3306/scorpian","root","1616");
                String sql;
                String scat="Phoenix";

                sql="insert into menu values('"+cat+"','"+scat+"',"+q+","+amt1+")";
                Statement st=con.createStatement();
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(null,"Phoenix added");

            }
            catch(Exception e)
            {JOptionPane.showMessageDialog(null,e.getMessage());
            }
        }
        if(c2.isSelected())
        {
            try
            {Class.forName("java.sql.DriverManager");
                Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/scorpian","root","1616");
                String sql;
                String sct="Guinness";

                sql="insert into menu values('"+cat+"','"+sct+"',"+qq+","+amt2+")";
                Statement st=con.createStatement();
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(null,"Guinness added");

            }
            catch(Exception e)
            {JOptionPane.showMessageDialog(null,e.getMessage());
            }
        }


        // TODO add your handling code here:
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        softdrink f=new softdrink();
        f.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
        hotbeverages f=new hotbeverages();
        f.setVisible(true);
        this.dispose();         // TODO add your handling code here:
    }

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {
        finalbill f=new finalbill();
        f.setVisible(true);
        this.dispose();      // TODO add your handling code here:
    }

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {
        hukka f=new hukka();
        f.setVisible(true);
        this.dispose();     // TODO add your handling code here:
    }

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {
        menu f=new menu();
        f.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(beers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(beers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(beers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(beers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new beers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JCheckBox c1;
    private javax.swing.JCheckBox c2;
    private javax.swing.JTextField j1;
    private javax.swing.JTextField j2;
    private javax.swing.JTextField j3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration
}
