
import javax.swing.*;
import java.awt.*;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Student
 */
public class homepage extends JFrame {

    /**
     * Creates new form homepage
     */
    public homepage() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jButton1 = new JButton();
        p1 = new JPasswordField();
        jTextField1 = new JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(1600, 1200);
        // Create a panel with absolute layout
        JPanel panel = new JPanel();
        panel.setLayout(null);

        jButton1.setBackground(new Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Informal Roman", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("LOGIN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.setBounds(690, 220, 120, 50);
        panel.add(jButton1);

        p1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p1ActionPerformed(evt);
            }
        });
        p1.setBounds(850, 140, 119, 30);
        panel.add(p1);
        jTextField1.setBounds(850, 80, 119, 30);
        panel.add(jTextField1);

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Algerian", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 204));
        jLabel2.setText("User Name");
        jLabel2.setBounds(670, 80, 170, 30);
       panel.add(jLabel2);

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Informal Roman", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("CLOSE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.setBounds(833, 220, 120, 50);
        panel.add(jButton2);

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Algerian", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setText("Password");
        jLabel3.setBounds(670, 140, 150, 30);
        panel.add(jLabel3);

        jLabel4.setFont(new java.awt.Font("Algerian", 2, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(79, 111, 238));
        jLabel4.setText("WELCOME");
        jLabel4.setBounds(350, 20, 280, 40);
        panel.add(jLabel4);

        ImageIcon imageIcon = new ImageIcon("C:\\Users\\bikku\\OneDrive\\Desktop\\hero-1.jpg");
        jLabel1.setIcon(imageIcon);
        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jLabel1.setText("User Name");
        jLabel1.setToolTipText("");
        jLabel1.setAlignmentY(0.0F);
        jLabel1.setDoubleBuffered(true);
        jLabel1.setFocusCycleRoot(true);
        jLabel1.setOpaque(true);
        jLabel1.setBounds(0,0,1600,1000);
        panel.add(jLabel1);
        // Add the panel to the frame
        getContentPane().add(panel);
        pack();
        setLocationRelativeTo(null);
        setVisible(true);
    }// </editor-fold>

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        String a= jTextField1.getText();
        String b= new String(p1.getPassword());
        if (b.equals("1234"))
        {     menu f;
            f = new menu();
            f.setVisible(true);
            this.dispose();
        }
        else
        { JOptionPane.showMessageDialog(null,"Password is Incorrect."+"\n"+" Try Again!");}

    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        System.exit(0);        // TODO add your handling code here:
    }

    private void p1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new homepage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPasswordField p1;
    // End of variables declaration
}
